##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = fenice-bms-lv


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Lib/can/lib/bms/bms_network.c \
Core/Lib/can/lib/bms/bms_watchdog.c \
Core/Lib/can/lib/inverters/inverters_network.c \
Core/Lib/can/lib/inverters/inverters_watchdog.c \
Core/Lib/can/lib/ivts/ivts_network.c \
Core/Lib/can/lib/ivts/ivts_watchdog.c \
Core/Lib/can/lib/primary/primary_network.c \
Core/Lib/can/lib/primary/primary_watchdog.c \
Core/Lib/can/lib/secondary/secondary_network.c \
Core/Lib/can/lib/secondary/secondary_watchdog.c \
Core/Lib/can/lib/simulator/simulator_network.c \
Core/Lib/can/lib/simulator/simulator_watchdog.c \
Core/Lib/invlib/inverter_conversions.c \
Core/Lib/micro-libs/bms-monitor/src/bms-monitor.c \
Core/Lib/micro-libs/bms-monitor/src/ltc6811.c \
Core/Lib/micro-libs/can-manager/src/can_manager.c \
Core/Lib/micro-libs/generic-queue/generic_queue.c \
Core/Lib/micro-libs/mcp23017/src/mcp23017.c \
Core/Lib/micro-libs/min-heap/src/min-heap.c \
Core/Lib/micro-libs/pid/pid.c \
Core/Lib/micro-libs/pwm/pwm.c \
Core/Lib/micro-libs/ring-buffer/src/ring-buffer.c \
Core/Lib/micro-libs/timer-utils/timer_utils.c \
Core/Lib/micro-libs/ucli/src/ucli-dictionary.c \
Core/Lib/micro-libs/ucli/src/ucli-fsm.c \
Core/Lib/micro-libs/ucli/src/ucli-parser.c \
Core/Lib/micro-libs/ucli/src/ucli.c \
Core/Src/adc.c \
Core/Src/bms_cli.c \
Core/Src/bms_fsm.c \
Core/Src/can.c \
Core/Src/can_messages.c \
Core/Src/cooling_control.c \
Core/Src/dac.c \
Core/Src/dac_pump.c \
Core/Src/dma.c \
Core/Src/error_simple.c \
Core/Src/gpio.c \
Core/Src/i2c.c \
Core/Src/main.c \
Core/Src/measure_check.c \
Core/Src/radiator.c \
Core/Src/spi.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_it.c \
Core/Src/system_stm32f4xx.c \
Core/Src/tim.c \
Core/Src/usart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c


CPP_SOURCES = \


# ASM sources
ASM_SOURCES =  \
startup_stm32f446xx.s



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
POSTFIX = "
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
GCC_PATH="/home/gmazzucchi/.config/Code/User/globalStorage/bmd.stm32-for-vscode/@xpack-dev-tools/arm-none-eabi-gcc/13.2.1-1.1.1/.content/bin
ifdef GCC_PATH
CXX = $(GCC_PATH)/$(PREFIX)g++$(POSTFIX)
CC = $(GCC_PATH)/$(PREFIX)gcc$(POSTFIX)
AS = $(GCC_PATH)/$(PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy$(POSTFIX)
SZ = $(GCC_PATH)/$(PREFIX)size$(POSTFIX)
else
CXX = $(PREFIX)g++
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DNOLOGGER \
-DSTM32F446xx \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32F446xx \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ICore/Lib/can/lib \
-ICore/Lib/can/lib/bms \
-ICore/Lib/can/lib/inverters \
-ICore/Lib/can/lib/ivts \
-ICore/Lib/can/lib/primary \
-ICore/Lib/can/lib/secondary \
-ICore/Lib/can/lib/simulator \
-ICore/Lib/can/proto/bms \
-ICore/Lib/can/proto/inverters \
-ICore/Lib/can/proto/ivts \
-ICore/Lib/can/proto/primary \
-ICore/Lib/can/proto/secondary \
-ICore/Lib/can/proto/simulator \
-ICore/Lib/invlib \
-ICore/Lib/micro-libs/CMock/examples/make_example/src \
-ICore/Lib/micro-libs/CMock/examples/temp_sensor/src \
-ICore/Lib/micro-libs/CMock/src \
-ICore/Lib/micro-libs/CMock/test/iar/iar_v4/incIAR \
-ICore/Lib/micro-libs/CMock/test/iar/iar_v5/incIAR \
-ICore/Lib/micro-libs/CMock/test/system/test_compilation \
-ICore/Lib/micro-libs/Unity/examples \
-ICore/Lib/micro-libs/Unity/examples/example_1/src \
-ICore/Lib/micro-libs/Unity/examples/example_2/src \
-ICore/Lib/micro-libs/Unity/examples/example_3/helper \
-ICore/Lib/micro-libs/Unity/examples/example_3/src \
-ICore/Lib/micro-libs/Unity/examples/example_4/src \
-ICore/Lib/micro-libs/Unity/extras/bdd/src \
-ICore/Lib/micro-libs/Unity/extras/fixture/src \
-ICore/Lib/micro-libs/Unity/extras/memory/src \
-ICore/Lib/micro-libs/Unity/extras/memory/test \
-ICore/Lib/micro-libs/Unity/src \
-ICore/Lib/micro-libs/Unity/test/expectdata \
-ICore/Lib/micro-libs/Unity/test/testdata \
-ICore/Lib/micro-libs/Unity/test/tests \
-ICore/Lib/micro-libs/blinky/inc \
-ICore/Lib/micro-libs/bms-monitor/inc \
-ICore/Lib/micro-libs/can-fifo-queue-legacy \
-ICore/Lib/micro-libs/can-fifo-queue-legacy/test \
-ICore/Lib/micro-libs/can-manager/inc \
-ICore/Lib/micro-libs/cli-legacy \
-ICore/Lib/micro-libs/eeprom-config \
-ICore/Lib/micro-libs/generic-queue \
-ICore/Lib/micro-libs/invlib \
-ICore/Lib/micro-libs/llist-legacy \
-ICore/Lib/micro-libs/llist-legacy/test \
-ICore/Lib/micro-libs/llist-legacy/test/munit \
-ICore/Lib/micro-libs/logger \
-ICore/Lib/micro-libs/m95256 \
-ICore/Lib/micro-libs/mcp23017/inc \
-ICore/Lib/micro-libs/min-heap/inc \
-ICore/Lib/micro-libs/pid \
-ICore/Lib/micro-libs/priority-queue \
-ICore/Lib/micro-libs/priority-queue/test \
-ICore/Lib/micro-libs/pwm \
-ICore/Lib/micro-libs/ring-buffer/inc \
-ICore/Lib/micro-libs/timer-utils \
-ICore/Lib/micro-libs/ucli/inc \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -feliminate-unused-debug-types

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf -ggdb
CXXFLAGS += -g -gdwarf -ggdb
endif

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F446RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -specs=nano.specs -u_printf_float 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of cpp program objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))

# list of C objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

# list of ASM program objects
UPPER_CASE_ASM_SOURCES = $(filter %.S,$(ASM_SOURCES))
LOWER_CASE_ASM_SOURCES = $(filter %.s,$(ASM_SOURCES))

OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(UPPER_CASE_ASM_SOURCES:.S=.o)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(LOWER_CASE_ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.cpp STM32Make.make | $(BUILD_DIR) 
	$(CXX) -c $(CXXFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.cxx STM32Make.make | $(BUILD_DIR) 
	$(CXX) -c $(CXXFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cxx=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.c STM32Make.make | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s STM32Make.make | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S STM32Make.make | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) STM32Make.make
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# flash
#######################################
flash: $(BUILD_DIR)/$(TARGET).elf
	"/home/gmazzucchi/.config/Code/User/globalStorage/bmd.stm32-for-vscode/@xpack-dev-tools/openocd/0.12.0-2.1/.content/bin/openocd" -f ./openocd.cfg -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: $(BUILD_DIR)/$(TARGET).elf
	"/home/gmazzucchi/.config/Code/User/globalStorage/bmd.stm32-for-vscode/@xpack-dev-tools/openocd/0.12.0-2.1/.content/bin/openocd" -f ./openocd.cfg -c "init; reset halt; stm32f4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# custom makefile rules
#######################################




#######################################
# formatt
#######################################
formatt: $(BUILD_DIR)/$(TARGET).elf
	clang-format -style=file -i Core/Inc/*.h && clang-format -style=file -i Core/Src/*.c
      
	
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***