all:
	gcc measure_check_test.c ../Lib/micro-libs/min-heap/src/min-heap.c ../Lib/micro-libs/ring-buffer/src/ring-buffer.c ../Src/measure_check.c ../Lib/micro-libs/Unity/src/unity.c ../Src/lv_errors.c -I../Lib/micro-libs/Unity/src/ -I../Inc -I../Lib/micro-libs/min-heap/inc -I../Lib/micro-libs/ring-buffer/inc -lm
