/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: porket

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.3.4
Generation date: 2023-10-06 14:40:30 +0200
Generated from: fsm.dot
The finite state machine has:
  4 states
  4 transition functions
Functions and types have been generated with prefix "bmslv_"
******************************************************************************/

#include "fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *bmslv_state_names[] = {"init", "run", "error", "charging"};

// List of state functions
state_func_t *const bmslv_state_table[BMSLV_NUM_STATES] = {
  bmslv_do_init,     // in state init
  bmslv_do_run,      // in state run
  bmslv_do_error,    // in state error
  bmslv_do_charging, // in state charging
};

// Table of transition functions
transition_func_t *const bmslv_transition_table[BMSLV_NUM_STATES][BMSLV_NUM_STATES] = {
  /* states:      init                 , run                  , error                , charging              */
  /* init     */ {NULL                 , bmslv_init_to_run    , bmslv_to_error       , NULL                 }, 
  /* run      */ {NULL                 , NULL                 , bmslv_to_error       , bmslv_run_to_charging}, 
  /* error    */ {NULL                 , NULL                 , NULL                 , NULL                 }, 
  /* charging */ {NULL                 , bmslv_charging_to_run, bmslv_to_error       , NULL                 }, 
};

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state init
// valid return states: BMSLV_STATE_RUN, BMSLV_STATE_ERROR
bmslv_state_t bmslv_do_init(bmslv_state_data_t *data) {
  bmslv_state_t next_state = BMSLV_STATE_RUN;
  
  /* Your Code Here */
  //

  next_state = BMSLV_STATE_RUN;
  
  switch (next_state) {
    case BMSLV_STATE_RUN:
    case BMSLV_STATE_ERROR:
      break;
    default:
      next_state = BMSLV_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state run
// valid return states: BMSLV_STATE_CHARGING, BMSLV_STATE_ERROR
bmslv_state_t bmslv_do_run(bmslv_state_data_t *data) {
  bmslv_state_t next_state = BMSLV_STATE_CHARGING;
  
  /* Your Code Here */
  
  switch (next_state) {
    case BMSLV_STATE_CHARGING:
    case BMSLV_STATE_ERROR:
      break;
    default:
      next_state = BMSLV_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state error
// valid return states: BMSLV_NO_CHANGE
bmslv_state_t bmslv_do_error(bmslv_state_data_t *data) {
  bmslv_state_t next_state = BMSLV_NO_CHANGE;
  
  /* Your Code Here */
  
  switch (next_state) {
    case BMSLV_NO_CHANGE:
      break;
    default:
      next_state = BMSLV_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state charging
// valid return states: BMSLV_STATE_RUN, BMSLV_STATE_ERROR
bmslv_state_t bmslv_do_charging(bmslv_state_data_t *data) {
  bmslv_state_t next_state = BMSLV_STATE_RUN;
  
  /* Your Code Here */
  
  switch (next_state) {
    case BMSLV_STATE_RUN:
    case BMSLV_STATE_ERROR:
      break;
    default:
      next_state = BMSLV_NO_CHANGE;
  }
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */    
                                         
// This function is called in 1 transition:
// 1. from init to run
void bmslv_init_to_run(bmslv_state_data_t *data) {
  /* Your Code Here */
}

// This function is called in 3 transitions:
// 1. from init to error
// 2. from run to error
// 3. from charging to error
void bmslv_to_error(bmslv_state_data_t *data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from run to charging
void bmslv_run_to_charging(bmslv_state_data_t *data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from charging to run
void bmslv_charging_to_run(bmslv_state_data_t *data) {
  /* Your Code Here */
}


/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

bmslv_state_t bmslv_run_state(bmslv_state_t cur_state, bmslv_state_data_t *data) {
  bmslv_state_t new_state = bmslv_state_table[cur_state](data);
  if (new_state == BMSLV_NO_CHANGE) new_state = cur_state;
  transition_func_t *transition = bmslv_transition_table[cur_state][new_state];
  if (transition)
    transition(data);
  return new_state;
};

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
  bmslv_state_t cur_state = BMSLV_STATE_INIT;
  do {
    cur_state = bmslv_run_state(cur_state, NULL);
    sleep(1);
  } while (cur_state != BMSLV_STATE_ERROR);
  bmslv_run_state(cur_state, NULL);
  return 0;
}
#endif
