#ifndef TIMER_UTILITY_H
#define TIMER_UTILITY_H

#include "tim.h"

// /* RAD_L      -> TIM3 CH1 */
// #define RAD_L_HTIM htim3
// #define RAD_L_PWM_TIM_CHNL TIM_CHANNEL_1
// /* RAD_R      -> TIM3 CH2 */
// #define RAD_R_HTIM htim3
// #define RAD_R_PWM_TIM_CHNL TIM_CHANNEL_2
// /* INTERNAL_FAN      -> TIM2 CH3 */
// #define INTERNAL_FAN_HTIM htim3
// #define INTERNAL_FAN_PWM_TIM_CHNL TIM_CHANNEL_3

// /* BUZZER    -> TIM8 CH1 */
// #define BZZR_HTIM htim8
// #define BZZR_PWM_TIM_CHNL TIM_CHANNEL_1
// #define BUZZER_ALARM_TIME 200

// /* PUMPS*/
// #define PUMP_DAC hdac
// #define PUMP_L_CHNL DAC_CHANNEL_2
// #define PUMP_R_CHNL DAC_CHANNEL_1

// /* MEASUREMENTS */
// #define MEASUREMENTS_TIMER htim2
// #define MEAS_ALL_ANALOG_SIGNALS_TIMER_CHANNEL TIM_CHANNEL_1
// #define MEAS_VOLTS_AND_TEMPS_TIMER_CHANNEL TIM_CHANNEL_2
// #define MEAS_LV_VERSION_AND_COOLING_TIMER_CHANNEL TIM_CHANNEL_3
// #define MEAS_CELL_TEMPS_TIMER_CHANNEL TIM_CHANNEL_4
// #define MEAS_ALL_ANALOG_SIGNALS_TIMER_ACTIVE_CHANNEL HAL_TIM_ACTIVE_CHANNEL_1
// #define MEAS_VOLTS_AND_TEMPS_TIMER_ACTIVE_CHANNEL HAL_TIM_ACTIVE_CHANNEL_2
// #define MEAS_LV_VERSION_AND_COOLING_TIMER_ACTIVE_CHANNEL \
//   HAL_TIM_ACTIVE_CHANNEL_3
// #define MEAS_CELL_TEMPS_TIMER_ACTIVE_CHANNEL HAL_TIM_ACTIVE_CHANNEL_4
// #define OPEN_WIRE_MEASUREMENT_TIMER htim4
// #define OPEN_WIRE_TIMER_CHANNEL TIM_CHANNEL_2
// #define OPEN_WIRE_TIMER_ACTIVE_CHANNEL HAL_TIM_ACTIVE_CHANNEL_2

// /* ERRORS TIMER */

// #define ERROR_TIMER_CHANNEL TIM_CHANNEL_1

// /* ADC TIMER */
// #define TIMER_ADC_MEAS htim10
// #define TIMER_ADC_CALIBRATION htim1
// #define TIMER_ADC_CALIBRATION_CHANNEL TIM_CHANNEL_1
// #define TIMER_ADC_CALIBRATION &htim1
// #define TIMER_ADC_ROUTINE &htim10
// #define TIMER_ADC_CALIBRATION_CHANNEL TIM_CHANNEL_1

#endif // TIMER_UTILITY_H